import { read, sourced } from "@/lib/claims";
import type { SourcesInput } from "@/lib/schema/public";

/**
 * Every source the audit cites, by id. Each one is dated (the day it was
 * read) and grouped for /sources. Where sources disagree, the conflict goes in
 * `caveats` rather than being quietly resolved.
 */
const accessed = "2026-10-08";

export default {
  items: [
    // ── ArcScore ────────────────────────────────────────────────────────────
    {
      id: "brief",
      title: "Founding Head of Growth (role brief, no public posting)",
      publisher: "The author",
      url: "https://arcscore.ai/",
      kind: "other",
      accessed,
      group: "ArcScore",
      note: "ArcScore is pre-launch and publishes no careers page or job postings. This brief is the author's own definition of the seat the audit reads the company through (content/jd.md). It is not a company statement.",
      confidence: "medium",
    },
    {
      id: "arc-site",
      title: "ArcScore: Know Your Worth. See Your Value.",
      publisher: "ArcScore",
      url: "https://arcscore.ai/",
      kind: "company-site",
      accessed,
      group: "ArcScore",
      note: "The home page is a client-rendered app. The meta description was read from the page head on 2026-10-08; the hero text for each audience (athletes, schools, brands) was read word for word from the page's JavaScript bundle the same day.",
    },
    {
      id: "arc-get-started",
      title: "Get Started | ArcScore",
      publisher: "ArcScore",
      url: "https://arcscore.ai/get-started/",
      kind: "company-site",
      accessed,
      group: "ArcScore",
    },

    {
      id: "arc-help",
      title: "Get Help",
      publisher: "ArcScore",
      url: "https://arcscore.ai/help/",
      kind: "company-site",
      accessed,
      group: "ArcScore",
    },
    {
      id: "form-d",
      title: "Form D notice of exempt offering: ArcScore, Inc.",
      publisher: "U.S. Securities and Exchange Commission (EDGAR)",
      url: "https://www.sec.gov/Archives/edgar/data/2141062/000214106226000001/primary_doc.xml",
      kind: "filing",
      published: "2026-06-22",
      accessed,
      group: "ArcScore",
      note: "A point-in-time filing. Amounts sold are as of the filing date and will have moved since. Personal addresses and phone numbers in the filing are deliberately not reproduced here.",
    },
    {
      id: "trademark",
      title: "ARCSCORE, U.S. trademark application serial 99560090",
      publisher: "U.S. Patent and Trademark Office (TSDR)",
      url: "https://tsdr.uspto.gov/statusview/sn99560090",
      kind: "filing",
      published: "2025-12-21",
      accessed,
      group: "ArcScore",
      note: "An intent-to-use application. Its list of services shows what ArcScore intends to offer, not what exists today.",
    },
    {
      id: "domain",
      title: "arcscore.ai domain registration record",
      publisher: "Identity Digital registry (RDAP)",
      url: "https://rdap.identitydigital.services/rdap/domain/arcscore.ai",
      kind: "dataset",
      accessed,
      group: "ArcScore",
    },
    {
      id: "bcp-bio",
      title: "Let It Shine: artists, speakers and performers",
      publisher: "Bellarmine College Preparatory",
      url: "https://www.bcp.org/giving/let-it-shine/let-it-shine-artists-speakers-and-performers",
      kind: "other",
      accessed,
      group: "ArcScore",
      note: "Undated event biography.",
      confidence: "medium",
    },
    {
      id: "outcome-summit",
      title: "The Outcome Summit, attendees",
      publisher: "The Outcome Summit",
      url: "https://www.outcomesummit.com/home/welcome?page=4",
      kind: "other",
      published: "2026-03",
      accessed,
      group: "ArcScore",
      confidence: "medium",
    },
    {
      id: "wingstop-cmo",
      title: "Wingstop appoints Maurice Cooper Senior Vice President and Chief Marketing Officer",
      publisher: "Wingstop via Franchising.com",
      url: "https://www.franchising.com/news/20180611_wingstop_appoints_maurice_cooper_senior_vice_presi.html",
      kind: "press-release",
      published: "2018-06-11",
      accessed,
      group: "The founder",
    },
    {
      id: "wingstop-cgo",
      title: "Wingstop appoints Chief Growth & Experience Officer and names leader of digital",
      publisher: "Wingstop via Franchising.com",
      url: "https://www.franchising.com/news/20190313_wingstop_appoints_chief_growth_amp_experience_offi.html",
      kind: "press-release",
      published: "2019-03-13",
      accessed,
      group: "The founder",
    },
    {
      id: "target-svp",
      title: "Target names Maurice Cooper senior vice president of marketing",
      publisher: "Target",
      url: "https://corporate.target.com/press/release/2020/09/target-names-maurice-cooper-senior-vice-president",
      kind: "press-release",
      published: "2020-09-02",
      accessed,
      group: "The founder",
    },
    {
      id: "bbw-cco",
      title: "Bath & Body Works appoints Maurice Cooper as Chief Customer Officer",
      publisher: "Bath & Body Works via GlobeNewswire",
      url: "https://www.globenewswire.com/en/news-release/2023/05/10/2665623/0/en/Bath-Body-Works-Appoints-Maurice-Cooper-as-Chief-Customer-Officer.html",
      kind: "press-release",
      published: "2023-05-10",
      accessed,
      group: "The founder",
    },

    // ── Rules and the market ────────────────────────────────────────────────
    {
      id: "house-settlement",
      title: "Final approval of House settlement reshapes college athletics landscape",
      publisher: "Bricker Graydon",
      url: "https://www.bricker.com/insights/publications/final-approval-of-house-settlement-reshapes-college-athletics-landscape",
      kind: "analyst",
      published: "2025-06-12",
      accessed,
      group: "Rules and the market",
    },
    {
      id: "roster-limits",
      title: "NCAA eliminates sport-specific scholarship caps, introduces roster limits under House settlement",
      publisher: "WRHI",
      url: "https://www.wrhi.com/2025/06/ncaa-eliminates-sport-specific-scholarship-caps-introduces-roster-limits-under-house-settlement-201334",
      kind: "news",
      published: "2025-06-24",
      accessed,
      group: "Rules and the market",
    },
    {
      id: "cap-2026",
      title: "College Sports Commission, NIL Go have cleared deals since launch",
      publisher: "On3 via Yahoo Sports",
      url: "https://sports.yahoo.com/articles/college-sports-commission-nil-cleared-172953644.html",
      kind: "news",
      published: "2026-07-08",
      accessed,
      group: "Rules and the market",
      note: "Headline as published names the total cleared ($355 million).",
    },
    {
      id: "csc-report",
      title: "NIL Data Report, July 8, 2026",
      publisher: "College Sports Commission",
      url: "https://assets.tina.io/29b83311-e587-42b1-861e-87ebde9aa253/NIL%20Data%20Report%20-%20July%208,%202026.pdf",
      kind: "dataset",
      published: "2026-07-08",
      accessed,
      group: "Rules and the market",
    },
    {
      id: "csc-jul-aug",
      title: "In a major increase, CSC clears NIL deals in July and August",
      publisher: "Associated Press via MyNorthwest",
      url: "https://mynorthwest.com/national/in-a-major-increase-csc-clears-more-than-227m-worth-of-nil-deals-in-july-and-august/4274070",
      kind: "news",
      published: "2026-09-09",
      accessed,
      group: "Rules and the market",
      note: "Headline as published: \"In a major increase, CSC clears more than $227M worth of NIL deals in July and August\".",
    },
    {
      id: "csc-georgia",
      title: "Arbitration involving University of Georgia student-athletes concludes after CSC clears agreements upon updated review",
      publisher: "College Sports Commission",
      url: "https://assets.tina.io/29b83311-e587-42b1-861e-87ebde9aa253/Arbitration%20Involving%20University%20of%20Georgia%20Student-Athletes%20Concludes%20After%20College%20Sports%20Commission%20Clears%20Agreements%20Upon%20Updated%20Review.pdf",
      kind: "press-release",
      published: "2026-06-08",
      accessed,
      group: "Rules and the market",
    },
    {
      id: "roc-update",
      title: "College Sports Commission updates its range of compensation analysis",
      publisher: "NIL Revolution (Troutman Pepper Locke)",
      url: "https://www.nilrevolution.com/2026/06/college-sports-commission-updates-its-range-of-compensation-analysis/",
      kind: "analyst",
      published: "2026-06-29",
      accessed,
      group: "Rules and the market",
    },
    {
      id: "csc-strain",
      title: "College Sports Commission's NIL clearinghouse strained by surge in school-linked deals",
      publisher: "CBS Sports",
      url: "https://www.cbssports.com/college-football/news/college-sports-commissions-nil-clearinghouse-strained/",
      kind: "news",
      published: "2026-03-10",
      accessed,
      group: "Rules and the market",
    },
    {
      id: "pcsa-senate",
      title: "Senate overwhelmingly passes Protect College Sports Act",
      publisher: "U.S. Senate Committee on Commerce, Science, and Transportation",
      url: "https://www.commerce.senate.gov/?p=57686",
      kind: "press-release",
      published: "2026-09-28",
      accessed,
      group: "Rules and the market",
    },
    {
      id: "pcsa-analysis",
      title: "The Protect College Sports Act clears the Senate: what stakeholders need to know",
      publisher: "Duane Morris",
      url: "https://blogs.duanemorris.com/sportslaw/2026/10/05/the-protect-college-sports-act-clears-the-senate-what-stakeholders-need-to-know/",
      kind: "analyst",
      published: "2026-10-05",
      accessed,
      group: "Rules and the market",
    },
    {
      id: "opendorse-report-2026",
      title: "2026 Annual NIL Report",
      publisher: "Opendorse",
      url: "https://biz.opendorse.com/wp-content/uploads/2026/06/AnnualNILReport_06222026.pdf",
      kind: "analyst",
      published: "2026-06-22",
      accessed,
      group: "Rules and the market",
      note: "Opendorse is also a competitor. Its market figures are used for scale, not as neutral fact.",
    },
    {
      id: "opendorse-market-blog",
      title: "The NIL market hit a new high: why everyone, including us, underestimated it",
      publisher: "Opendorse",
      url: "https://biz.opendorse.com/blog/nil-market-size-2026/",
      kind: "analyst",
      published: "2026-07-22",
      accessed,
      group: "Rules and the market",
      note: "Headline as published: \"The NIL Market Hit $4.5B: Here's Why Everyone (Including Us) Underestimated It\".",
    },
    {
      id: "revshare-split",
      title: "College hoops accounts for nearly a third of revenue-sharing payments",
      publisher: "Front Office Sports",
      url: "https://frontofficesports.com/article/college-hoops-accounts-for-nearly-30-of-revenue-sharing-payments/",
      kind: "news",
      published: "2025-11-04",
      accessed,
      group: "Rules and the market",
      note: "Headline as published: \"College Hoops Accounts for Nearly 30% of Revenue-Sharing Payments\".",
    },
    {
      id: "schools-agencies",
      title: "How schools are skirting the new salary cap in college sports",
      publisher: "Front Office Sports",
      url: "https://frontofficesports.com/article/schools-skirting-salary-cap-college-sports/",
      kind: "news",
      published: "2025-09-20",
      accessed,
      group: "Rules and the market",
    },
    {
      id: "espn-volleyball",
      title: "ESPN delivered most-watched women's college volleyball season on record",
      publisher: "ESPN Press Room",
      url: "https://espnpressroom.com/us/press-releases/2025/12/espn-delivers-most-watched-womens-college-volleyball-season-on-record/",
      kind: "press-release",
      published: "2025-12-05",
      accessed,
      group: "Rules and the market",
    },
    {
      id: "learfield-women",
      title: "Female athletes surge in NIL deals as Learfield reports a jump in participation",
      publisher: "Associated Press via News4JAX",
      url: "https://www.news4jax.com/sports/2026/07/28/female-athletes-surge-in-nil-deals-as-learfield-reports-a-123-jump-in-participation/",
      kind: "news",
      published: "2026-07-28",
      accessed,
      group: "Rules and the market",
    },
    {
      id: "brands-march",
      title: "The real winners of March Madness: brands that move fast on NIL deals",
      publisher: "Modern Retail",
      url: "https://www.modernretail.co/marketing/the-real-winners-of-march-madness-brands-that-move-fast-on-nil-deals/",
      kind: "news",
      published: "2026-03-18",
      accessed,
      group: "Rules and the market",
    },
    {
      id: "brands-women",
      title: "Fashion and beauty brands are expanding their partnerships with female college athletes",
      publisher: "Modern Retail",
      url: "https://www.modernretail.co/marketing/fashion-and-beauty-brands-are-expanding-their-partnerships-with-female-college-athletes/",
      kind: "news",
      published: "2026-01-08",
      accessed,
      group: "Rules and the market",
    },
    {
      id: "nil-recall",
      title: "How good are NIL deals for brands looking to invest in athletes?",
      publisher: "Morning Consult",
      url: "https://intel.morningconsult.com/mc-content/analysis/nil-college-athletes-public-opinion-brand-strategy-2025",
      kind: "analyst",
      published: "2025-03-27",
      accessed,
      group: "Rules and the market",
    },

    // ── Competitors ─────────────────────────────────────────────────────────
    {
      id: "teamworks-personnel",
      title: "Personnel: roster planning, general manager and valuation tools",
      publisher: "Teamworks",
      url: "https://teamworks.com/personnel",
      kind: "company-site",
      accessed,
      group: "Competitors",
    },
    {
      id: "teamworks-series-f",
      title: "Teamworks raises Series F to accelerate AI-powered innovation",
      publisher: "Teamworks",
      url: "https://teamworks.com/blog/teamworks-series-f/",
      kind: "press-release",
      published: "2025-06-17",
      accessed,
      group: "Competitors",
      note: "Headline as published: \"Teamworks Raises $235M to Accelerate AI-Powered Innovation\".",
    },
    {
      id: "teamworks-sportlogiq",
      title: "Teamworks acquires Sportlogiq",
      publisher: "Teamworks",
      url: "https://teamworks.com/blog/teamworks-acquires-sportlogiq",
      kind: "press-release",
      published: "2026-01-15",
      accessed,
      group: "Competitors",
    },
    {
      id: "teamworks-pff",
      title: "Teamworks acquires PFF's enterprise business",
      publisher: "Teamworks",
      url: "https://teamworks.com/blog/teamworks-acquires-pff-enterprise/",
      kind: "press-release",
      published: "2026-03-30",
      accessed,
      group: "Competitors",
    },
    {
      id: "teamworks-murray",
      title: "Murray State Athletics announces expanded partnership with Teamworks",
      publisher: "Murray State Athletics",
      url: "https://goracers.com/news/2026/7/8/general-murray-state-athletics-announces-expanded-partnership-with-teamworks",
      kind: "press-release",
      published: "2026-07-08",
      accessed,
      group: "Competitors",
    },
    {
      id: "dropback-yc",
      title: "Dropback: the front office software suite for college sports",
      publisher: "Y Combinator",
      url: "https://www.ycombinator.com/companies/dropback",
      kind: "company-site",
      accessed,
      group: "Competitors",
    },
    {
      id: "dropback-sis",
      title: "Sports Info Solutions and Dropback partner to power data-driven roster valuations for college general managers",
      publisher: "Sports Info Solutions",
      url: "https://www.sportsinfosolutions.com/?p=9288",
      kind: "press-release",
      published: "2026-03-03",
      accessed,
      group: "Competitors",
    },
    {
      id: "dropback-hudl",
      title: "Hudl and Dropback partner",
      publisher: "Hudl",
      url: "https://www.hudl.com/blog/hudl-dropback-partner",
      kind: "press-release",
      published: "2026-08-20",
      accessed,
      group: "Competitors",
    },
    {
      id: "sas-msu",
      title: "Michigan State partners with Student Athlete Score to elevate NIL strategy",
      publisher: "Michigan State Athletics",
      url: "https://msuspartans.com/news/2025/10/1/general-michigan-state-partners-with-student-athlete-score-to-elevate-nil-strategy",
      kind: "press-release",
      published: "2025-10-01",
      accessed,
      group: "Competitors",
    },
    {
      id: "sas-fairfield",
      title: "Fairfield University partners with Student Athlete Score to elevate NIL strategy",
      publisher: "Fairfield Athletics",
      url: "https://fairfieldstags.com/news/2025/10/16/general-fairfield-university-partners-with-student-athlete-score-to-elevate-nil-strategy.aspx",
      kind: "press-release",
      published: "2025-10-16",
      accessed,
      group: "Competitors",
    },
    {
      id: "sas-mason",
      title: "George Mason Athletics partners with Student Athlete Score",
      publisher: "George Mason Athletics",
      url: "https://gomason.com/news/2025/11/14/athletics-score.aspx",
      kind: "press-release",
      published: "2025-11-14",
      accessed,
      group: "Competitors",
    },
    {
      id: "opendorse-sanil",
      title: "Opendorse is taking over parts of failed NIL collective operator SANIL",
      publisher: "Front Office Sports",
      url: "https://frontofficesports.com/article/opendorse-is-taking-over-parts-of-failed-nil-collective-operator-sanil/",
      kind: "news",
      published: "2025-10-02",
      accessed,
      group: "Competitors",
    },
    {
      id: "opendorse-heartland",
      title: "Heartland Collegiate Athletic Conference partners with Opendorse",
      publisher: "Heartland Conference",
      url: "https://heartlandconf.org/news/2026/4/9/general-heartland-collegiate-athletic-conference-partners-with-opendorse-to-advance-nil-strategy-innovation-and-support.aspx",
      kind: "press-release",
      published: "2026-04-09",
      accessed,
      group: "Competitors",
    },
    {
      id: "opendorse-one",
      title: "Opendorse ties college athlete influencer content to retail media purchases with new product launch",
      publisher: "Net Influencer",
      url: "https://www.netinfluencer.com/opendorse-ties-college-athlete-influencer-content-to-retail-media-purchases-with-new-product-launch/",
      kind: "news",
      published: "2026-06-19",
      accessed,
      group: "Competitors",
    },
    {
      id: "out2win-seed",
      title: "Out2Win secures seed round",
      publisher: "Athletech News",
      url: "https://athletechnews.com/out2win-secures-1-3m-seed-round/",
      kind: "news",
      published: "2025-03-14",
      accessed,
      group: "Competitors",
    },
    {
      id: "out2win-syracuse",
      title: "Syracuse partners with Out2Win to expand NIL opportunities for student-athletes",
      publisher: "Syracuse Athletics",
      url: "https://cuse.com/news/2026/2/10/general-syracuse-partners-with-out2win-to-expand-nil-opportunities-for-student-athletes",
      kind: "press-release",
      published: "2026-02-10",
      accessed,
      group: "Competitors",
    },
    {
      id: "on3-valuation-shift",
      title: "ACC QB revealed to have No. 1 NIL valuation in college football",
      publisher: "Sports Illustrated (FanNation)",
      url: "https://www.si.com/fannation/college/cfb-hq/news/acc-qb-Darian-mensah-have-no-1-nil-valuation-in-college-football",
      kind: "news",
      published: "2026-07-15",
      accessed,
      group: "Competitors",
      note: "Quotes On3's own description of the July 1, 2026 change. On3's methodology page returned 403 when fetched.",
    },
    {
      id: "nilclub-newsroom",
      title: "NIL Club newsroom",
      publisher: "NIL Club",
      url: "https://nilclub.com/business/newsroom",
      kind: "company-site",
      accessed,
      group: "Competitors",
    },
    {
      id: "learfield-media-days",
      title: "Inside Tennessee's NIL carwash day, a multimedia smorgasbord to help athletes cash in",
      publisher: "Associated Press via La Nación",
      url: "https://www.lanacion.com.ar/usa/inside-tennessees-nil-carwash-day-a-multimedia-smorgasbord-to-help-athletes-cash-in-nid19082026/",
      kind: "news",
      published: "2026-08-19",
      accessed,
      group: "Competitors",
      note: "The ABC News copy of this AP story no longer resolves; this mirror carries the same text.",
      confidence: "medium",
    },
  ],
  caveats: [
    sourced(
      "Opendorse's report says its $4.5B 2026-27 estimate is a 50% increase on earlier projections; its July blog post says about 61%. Some press describes the figure as money paid to athletes, while Opendorse defines it as total spend on NIL products and services. This audit uses $4.5B for scale only.",
      ["opendorse-report-2026", "opendorse-market-blog"],
    ),
    sourced(
      "Clearinghouse speed figures move between reports: the July 2026 data report says 63% of deals resolved within seven days, and the AP's September report says 68% for July and August. The audit cites each with its window.",
      ["csc-report", "csc-jul-aug"],
    ),
    read(
      "The College Sports Commission's range-of-compensation check applies to deals with entities tied to a school; deals with unaffiliated brands get minimal review, and from July 2026 most associated deals under $15,000 skip the range check. The audit's compliance arguments apply to school-tied deals only.",
      { sources: ["opendorse-report-2026", "roc-update"] },
    ),
    read(
      "ArcScore is pre-launch and has published almost nothing. Anything here about its product, buyers or plans beyond its own site is an outside-in read.",
    ),
    read(
      "Competitors with no dated public move between October 2025 and October 2026 were left off the map, including MOGL, Icon Source, NOCAP Sports and Dreamfield. Cache AI and Datavault were also left off: their moves were early or unconfirmed.",
    ),
    read("Everything marked as an outside-in read is inference, not inside knowledge. Illustrative models use invented numbers."),
  ],
} satisfies SourcesInput;
